export const Paths = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CONNECTORS: '/connectors',
  SETTINGS: '/setting',
  GI: '/general-information',
  SETTINGS_RESIDENT_POSTS: '/setting/resident-posts',
  SETTINGS_RESIDENT: '/setting/residents',
  CHAT: '/chat',
  CALENDAR: '/calendar',
  MAP_VIEW: '/mapview',
  REQUESTS: '/requests',
  APPRECIATIONS: '/appreciations',
  ALERTS: '/alerts',
  INVOICES: '/invoices',
  PAYMENT_METHOD: '/payment-method',
  SUGGESTIONS: '/suggestions',
  DEPARTMENTS: '/departments',
  SUBSCRIPTIONS: '/subscriptions',
  SUBSCRIPTION: '/subscription',
  EMPLOYEES: '/employees',
  RESIDENTS: '/residents',
  RESIDENT_POSTS: '/resident-posts',
  WORKLOGS: '/worklogs',
  TASKS: '/tasks',
}
