export const menus = {
  TITLE_MENU: {
    Services: 'services_live',
    Account: 'account',
    Social: 'addon_social',
    Activity: 'activity_live',
    Operations: 'operations_live',
    Resources: 'resource_live',
    Facilities: 'facilities_live',
    Reporting: 'addon_reporting',
    CityPosts: 'cityposts',
    Support: 'Support_live',
  },
  MAIN_MENU: {
    Dashboard: 'dashboard_live',
    Setting: 'profile_setting',
    Calendar: 'calendar_live',
    Chat: 'chat_live',
  },
  SUB_MENU: {
    GI: 'GI_live',
    text: 'text_live',
    Report_Bug: 'report_bug',
    Suggest_Feature: 'suggest_feature',
    Live_Chat: 'content_livechat',
    Subscription: 'subscription_live',
    Invoices: 'invoices_live',
    PaymentMethod: 'paymentmethod_live',
    Residents: 'residents_live',
    ResidentPosts: 'residentposts',
    Alerts: 'preference_alerts',
    Proposals: 'proposals_title_text',
    Events: 'events_title_text',
    Worklogs: 'worklogs_live',
    Tasks: 'tasks_title_text',
    Inspections: 'inspections_title_text',
    Routes: 'routes_live',
    Playbooks: 'playbooks_live',
    Employees: 'employees',
    Departments: 'departments_live',
    Vehicles: 'Vehiclesmenu_live',
    ToolsEquipment: 'Tools_equipmentmenu_live',
    Assets: 'assets',
    Infrastructure: 'infrastructure_title_text',
    CustomMetrics: 'custom_metrics_live',
    Notificiation: 'notificiation_live',
    Trips: 'trips_live',
    MUNICIPALTAXES: 'municipan_taxes_live',
    PARKINGFINES: 'parking_fines',
    Requests: 'requests_title_text',
    Appreciations: 'text_appreciations',
    Districts: 'districts_live',
    Suggestions: 'suggestions',
  },
}
