export const plans = {
  freePlan: [
    {
      title: 'resident',
      icon: 'plans_icons/user_resident_icon',
      unitPer: 10,
    },
    {
      title: 'requests_live',
      icon: 'plans_icons/feature_icon_request_black',
      unitPer: 10,
    },
    {
      title: 'Suggestions_live',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: 10,
    },
    {
      title: 'appreciations',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: 10,
    },
    {
      title: 'tasks_live',
      icon: 'plans_icons/feature_icon_task',
      unitPer: 10,
    },
    {
      title: 'worklogs_live',
      icon: 'plans_icons/feature_icon_worklog',
      unitPer: 10,
    },
    {
      title: 'employees',
      icon: 'plans_icons/user_colleague_icon',
      unitPer: 10,
    },
    {
      title: 'departments_live',
      icon: 'plans_icons/department_icon',
      unitPer: 10,
    },
    {
      title: 'chat_live',
      icon: 'plans_icons/feature_icon_chat',
      unitPer: 10,
    },
  ],
  engagePlan: [
    {
      title: 'resident_live',
      icon: 'plans_icons/user_resident_icon',
      unitPer: '1 to 100',
      pricePer: '$0.00',
    },
    {
      title: 'resident_live',
      icon: 'plans_icons/user_resident_icon',
      unitPer: '101 to 1000',
      pricePer: '$0.10',
    },
    {
      title: 'resident_live',
      icon: 'plans_icons/user_resident_icon',
      unitPer: '1001 to 2500',
      pricePer: '$0.05',
    },
    {
      title: 'resident_live',
      icon: 'plans_icons/user_resident_icon',
      unitPer: 'for_the_rest',
      pricePer: '$0.025',
    },
    {
      title: 'requests_live',
      icon: 'plans_icons/feature_icon_request_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'requests_live',
      icon: 'plans_icons/feature_icon_request_black',
      unitPer: '11 to 1000',
      pricePer: '$0.25',
    },
    {
      title: 'requests_live',
      icon: 'plans_icons/feature_icon_request_black',
      unitPer: '1001 to 2500',
      pricePer: '$0.15',
    },
    {
      title: 'requests_live',
      icon: 'plans_icons/feature_icon_request_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
    {
      title: 'Suggestions_live',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'Suggestions_live',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '11 to 50',
      pricePer: '$0.25',
    },
    {
      title: 'Suggestions_live',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '51 to 100',
      pricePer: '$0.15',
    },
    {
      title: 'Suggestions_live',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
    {
      title: 'appreciations',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'appreciations',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '11 to 50',
      pricePer: '$0.25',
    },
    {
      title: 'appreciations',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '51 to 100',
      pricePer: '$0.15',
    },
    {
      title: 'appreciations',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
  ],
  acceleratePlan: [
    {
      title: 'employee',
      icon: 'plans_icons/user_colleague_icon',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'employee',
      icon: 'plans_icons/user_colleague_icon',
      unitPer: '11 to 50',
      pricePer: '$20.00',
    },
    {
      title: 'employee',
      icon: 'plans_icons/user_colleague_icon',
      unitPer: '51 to 100',
      pricePer: '$15.00',
    },
    {
      title: 'employee',
      icon: 'plans_icons/user_colleague_icon',
      unitPer: 'for_the_rest',
      pricePer: '$10.00',
    },
    {
      title: 'proposals_live',
      icon: 'plans_icons/feature_icon_proposal',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'proposals_live',
      icon: 'plans_icons/feature_icon_proposal',
      unitPer: '11 to 25',
      pricePer: '$20.00',
    },
    {
      title: 'proposals_live',
      icon: 'plans_icons/feature_icon_proposal',
      unitPer: '26 to 50',
      pricePer: '$15.00',
    },
    {
      title: 'proposals_live',
      icon: 'plans_icons/feature_icon_proposal',
      unitPer: 'for_the_rest',
      pricePer: '$10.00',
    },
    {
      title: 'Alertsmenu_live',
      icon: 'plans_icons/feature_icon_alert',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'Alertsmenu_live',
      icon: 'plans_icons/feature_icon_alert',
      unitPer: '11 to 50',
      pricePer: '$20.00',
    },
    {
      title: 'Alertsmenu_live',
      icon: 'plans_icons/feature_icon_alert',
      unitPer: '51 to 100',
      pricePer: '$15.00',
    },
    {
      title: 'Alertsmenu_live',
      icon: 'plans_icons/feature_icon_alert',
      unitPer: 'for_the_rest',
      pricePer: '$10.00',
    },
    {
      title: 'events_live',
      icon: 'plans_icons/suggestion_event_icon_black',
      unitPer: '1 to 10',
      pricePer: '$25.00',
    },
    {
      title: 'events_live',
      icon: 'plans_icons/suggestion_event_icon_black',
      unitPer: '11 to 50',
      pricePer: '$15.00',
    },
    {
      title: 'events_live',
      icon: 'plans_icons/suggestion_event_icon_black',
      unitPer: '51 to 100',
      pricePer: '$10.00',
    },
    {
      title: 'events_live',
      icon: 'plans_icons/suggestion_event_icon_black',
      unitPer: 'for_the_rest',
      pricePer: '$5.00',
    },
  ],
  propelPlan: [
    {
      title: 'worklogs_live',
      icon: 'plans_icons/feature_icon_worklog',
      unitPer: '1 to 100',
      pricePer: '$2.50',
    },
    {
      title: 'worklogs_live',
      icon: 'plans_icons/feature_icon_worklog',
      unitPer: '11 to 50',
      pricePer: '$2.00',
    },
    {
      title: 'worklogs_live',
      icon: 'plans_icons/feature_icon_worklog',
      unitPer: '51 to 100',
      pricePer: '$1.50',
    },
    {
      title: 'worklogs_live',
      icon: 'plans_icons/feature_icon_worklog',
      unitPer: 'for_the_rest',
      pricePer: '$1.00',
    },
    {
      title: 'infrastructure_live',
      icon: 'plans_icons/feature_icon_infrastructure2',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'infrastructure_live',
      icon: 'plans_icons/feature_icon_infrastructure2',
      unitPer: '11 to 1000',
      pricePer: '$0.25',
    },
    {
      title: 'infrastructure_live',
      icon: 'plans_icons/feature_icon_infrastructure2',
      unitPer: '1001 to 2500',
      pricePer: '$0.10',
    },
    {
      title: 'infrastructure_live',
      icon: 'plans_icons/feature_icon_infrastructure2',
      unitPer: 'for_the_rest',
      pricePer: '$0.05',
    },
    {
      title: 'assets_live',
      icon: 'plans_icons/feature_icon_asset',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'Asset',
      icon: 'plans_icons/feature_icon_asset',
      unitPer: '11 to 1000',
      pricePer: '$0.25',
    },
    {
      title: 'assets_live',
      icon: 'plans_icons/feature_icon_asset',
      unitPer: '1001 to 2500',
      pricePer: '$0.10',
    },
    {
      title: 'assets_live',
      icon: 'plans_icons/feature_icon_asset',
      unitPer: 'for_the_rest',
      pricePer: '$0.00',
    },
    {
      title: 'inspections_live',
      icon: 'plans_icons/feature_icon_inspection',
      unitPer: '1 to 10',
      pricePer: '$25.00',
    },
    {
      title: 'inspections_live',
      icon: 'plans_icons/feature_icon_inspection',
      unitPer: '11 to 1000',
      pricePer: '$0.15',
    },
    {
      title: 'inspections_live',
      icon: 'plans_icons/feature_icon_inspection',
      unitPer: '1001 to 2500',
      pricePer: '$0.10',
    },
    {
      title: 'inspections_live',
      icon: 'plans_icons/feature_icon_inspection',
      unitPer: 'for_the_rest',
      pricePer: '$0.05',
    },
  ],
  delightPlan: [
    {
      title: 'tasks_live',
      icon: 'plans_icons/feature_icon_task',
      unitPer: '1 to 100',
      pricePer: '$0.00',
    },
    {
      title: 'tasks_live',
      icon: 'plans_icons/feature_icon_task',
      unitPer: '11 to 1000',
      pricePer: '$0.15',
    },
    {
      title: 'tasks_live',
      icon: 'plans_icons/feature_icon_task',
      unitPer: '1001 to 2500',
      pricePer: '$0.10',
    },
    {
      title: 'tasks_live',
      icon: 'plans_icons/feature_icon_task',
      unitPer: 'for_the_rest',
      pricePer: '$0.05',
    },
    {
      title: 'Vehiclesmenu_live',
      icon: 'plans_icons/feature_icon_vehicle_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'Vehiclesmenu_live',
      icon: 'plans_icons/feature_icon_vehicle_black',
      unitPer: '11 to 1000',
      pricePer: '$0.25',
    },
    {
      title: 'Vehiclesmenu_live',
      icon: 'plans_icons/feature_icon_vehicle_black',
      unitPer: '1001 to 2500',
      pricePer: '$0.15',
    },
    {
      title: 'Vehiclesmenu_live',
      icon: 'plans_icons/feature_icon_vehicle_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
    {
      title: 'ibeacon',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'ibeacon',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '11 to 50',
      pricePer: '$0.25',
    },
    {
      title: 'ibeacon',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: '51 to 100',
      pricePer: '$0.15',
    },
    {
      title: 'ibeacon',
      icon: 'plans_icons/feature_icon_suggestion_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
    {
      title: 'routes_live',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '1 to 10',
      pricePer: '$0.00',
    },
    {
      title: 'routes_live',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '11 to 50',
      pricePer: '$0.25',
    },
    {
      title: 'routes_live',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: '51 to 100',
      pricePer: '$0.15',
    },
    {
      title: 'routes_live',
      icon: 'plans_icons/feature_icon_appreciation_black',
      unitPer: 'for_the_rest',
      pricePer: '$0.10',
    },
  ],
}
