import React from 'react'

import { menus } from 'src/constants/menu'

import { ReactComponent as GI } from '../src/assets/svgs/settingSidebar/feature_icon_general_info.svg'
import { ReactComponent as Social } from '../src/assets/svgs/settingSidebar/feature_icon_socials.svg'
import { ReactComponent as Subscription } from '../src/assets/svgs/settingSidebar/feature_icon_subscription.svg'
import { ReactComponent as PaymentMethod } from '../src/assets/svgs/settingSidebar/payment_cards_icon.svg'
import { ReactComponent as PaymentInvoice } from '../src/assets/svgs/settingSidebar/payment_invoice_icon.svg'
import { ReactComponent as Account } from '../src/assets/svgs/settingSidebar/profile_account_icon.svg'
import { ReactComponent as Residents } from '../src/assets/svgs/settingSidebar/residents.svg'
import { ReactComponent as ResidentPosts } from '../src/assets/svgs/settingSidebar/send_icon.svg'
import { Paths } from './routes/paths'
const { TITLE_MENU, SUB_MENU } = menus
const primaryColor = { fill: '#1976D2' }
const primaryLightColor = { fill: '#A6D7FF' }
const blackColor = { fill: '#4F4F4F' }
const whiteColor = { fill: 'white' }

export const sidebarSettingRoutes: any = [
  {
    name: TITLE_MENU.Account,
    nameIcon: <Account style={whiteColor} />,
    nameIconBlack: <Account style={blackColor} />,
    menu: [
      {
        name: SUB_MENU.GI,
        icon: <GI style={whiteColor} />,
        iconBlue: <GI style={primaryColor} />,
        iconLightBlue: <GI style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isWorking: true, // route is working then flag is true otherwise false
        isActionAvailable: false,
        routePath: Paths.GI,
      },
      {
        name: SUB_MENU.Subscription,
        icon: <Subscription style={whiteColor} />,
        iconBlue: <Subscription style={primaryColor} />,
        iconLightBlue: <Subscription style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isActionAvailable: false,
        isWorking: true,
        routePath: Paths.SUBSCRIPTION,
      },
      {
        name: SUB_MENU.Invoices,
        icon: <PaymentInvoice style={whiteColor} />,
        iconBlue: <PaymentInvoice style={primaryColor} />,
        iconLightBlue: <PaymentInvoice style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isWorking: true,
        isActionAvailable: false,
        routePath: Paths.INVOICES,
      },
      {
        name: SUB_MENU.PaymentMethod,
        icon: <PaymentMethod style={whiteColor} />,
        iconBlue: <PaymentMethod style={primaryColor} />,
        iconLightBlue: <PaymentMethod style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isActionAvailable: false,
        isWorking: true,
        routePath: Paths.PAYMENT_METHOD,
      },
    ],
  },
  {
    name: TITLE_MENU.Social,
    nameIcon: <Social style={whiteColor} />,
    nameIconBlack: <Social style={blackColor} />,
    menu: [
      {
        name: SUB_MENU.Residents,
        icon: <Residents style={whiteColor} />,
        iconBlue: <Residents style={primaryColor} />,
        iconLightBlue: <Residents style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isWorking: true,
        isActionAvailable: false,
        routePath: Paths.SETTINGS_RESIDENT,
      },
      {
        name: SUB_MENU.ResidentPosts,
        icon: <ResidentPosts style={whiteColor} />,
        iconBlue: <ResidentPosts style={primaryColor} />,
        iconLightBlue: <ResidentPosts style={primaryLightColor} />,
        description: '',
        isHideMobile: false,
        isWorking: true,
        isActionAvailable: false,
        routePath: Paths.SETTINGS_RESIDENT_POSTS,
      },
      // {
      //   name: SUB_MENU.Alerts,
      //   icon: <Alerts style={whiteColor} />,
      //   iconBlue: <Alerts style={primaryColor} />,
      //   iconLightBlue: <Alerts style={primaryLightColor} />,
      //   description: '',
      //   isHideMobile: false,
      //   isActionAvailable: false,
      //   isWorking: true,
      //   routePath: toLowerCaseReplace(SUB_MENU.Alerts),
      // },
      // {
      //   name: SUB_MENU.Proposals,
      //   icon: <Proposals style={whiteColor} />,
      //   iconBlue: <Proposals style={primaryColor} />,
      //   iconLightBlue: <Proposals style={primaryLightColor} />,
      //   description: '',
      //   isHideMobile: false,
      //   isActionAvailable: false,
      //   isWorking: false,
      //   routePath: toLowerCaseReplace(SUB_MENU.Proposals),
      // },
      // {
      //   name: SUB_MENU.Events,
      //   icon: <Events style={whiteColor} />,
      //   iconBlue: <Events style={primaryColor} />,
      //   iconLightBlue: <Events style={primaryLightColor} />,
      //   description: '',
      //   isHideMobile: false,
      //   isActionAvailable: false,
      //   isWorking: false,
      //   routePath: toLowerCaseReplace(SUB_MENU.Events),
      // },
    ],
  },
  // {
  //   name: TITLE_MENU.Operations,
  //   nameIcon: <Operations style={whiteColor} />,
  //   nameIconBlack: <Operations style={blackColor} />,
  //   menu: [
  //     {
  //       name: SUB_MENU.Worklogs,
  //       icon: <Worklogs style={whiteColor} />,
  //       iconBlue: <Worklogs style={primaryColor} />,
  //       iconLightBlue: <Worklogs style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: true,
  //       routePath: toLowerCaseReplace(SUB_MENU.Worklogs),
  //     },
  //     {
  //       name: SUB_MENU.Tasks,
  //       icon: <Tasks style={whiteColor} />,
  //       iconBlue: <Tasks style={primaryColor} />,
  //       iconLightBlue: <Tasks style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Tasks),
  //     },
  //     {
  //       name: SUB_MENU.Inspections,
  //       icon: <Inspections style={whiteColor} />,
  //       iconBlue: <Inspections style={primaryColor} />,
  //       iconLightBlue: <Inspections style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Inspections),
  //     },
  //     {
  //       name: SUB_MENU.Routes,
  //       icon: <Routes style={whiteColor} />,
  //       iconBlue: <Routes style={primaryColor} />,
  //       iconLightBlue: <Routes style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Routes),
  //     },
  //     {
  //       name: SUB_MENU.Playbooks,
  //       icon: <Playbooks style={whiteColor} />,
  //       iconBlue: <Playbooks style={primaryColor} />,
  //       iconLightBlue: <Playbooks style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Playbooks),
  //     },
  //   ],
  // },
  // {
  //   name: TITLE_MENU.Resources,
  //   nameIcon: <Resources style={whiteColor} />,
  //   nameIconBlack: <Resources style={blackColor} />,
  //   menu: [
  //     {
  //       name: SUB_MENU.Employees,
  //       icon: <Employees style={whiteColor} />,
  //       iconBlue: <Employees style={primaryColor} />,
  //       iconLightBlue: <Employees style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: true,
  //       routePath: toLowerCaseReplace(SUB_MENU.Employees),
  //     },
  //     {
  //       name: SUB_MENU.Departments,
  //       icon: <Departments style={whiteColor} />,
  //       iconBlue: <Departments style={primaryColor} />,
  //       iconLightBlue: <Departments style={primaryLightColor} />,
  //       description:
  //         'Manage the Operating Departments within your City.  Commonly used departments have already been created. Assign directors to each, and they’ll invite their managers and employees.',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: true,
  //       routePath: toLowerCaseReplace(SUB_MENU.Departments),
  //     },
  //     {
  //       name: SUB_MENU.Vehicles,
  //       icon: <Vehicles style={whiteColor} />,
  //       iconBlue: <Vehicles style={primaryColor} />,
  //       iconLightBlue: <Vehicles style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Vehicles),
  //     },
  //     {
  //       name: SUB_MENU.ToolsEquipment,
  //       icon: <ToolsEquipment style={whiteColor} />,
  //       iconBlue: <ToolsEquipment style={primaryColor} />,
  //       iconLightBlue: <ToolsEquipment style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.ToolsEquipment),
  //     },
  //   ],
  // },
  // {
  //   name: TITLE_MENU.Facilities,
  //   nameIcon: <Facilities style={whiteColor} />,
  //   nameIconBlack: <Facilities style={blackColor} />,
  //   menu: [
  //     {
  //       name: SUB_MENU.Assets,
  //       icon: <Assets style={whiteColor} />,
  //       iconBlue: <Assets style={primaryColor} />,
  //       iconLightBlue: <Assets style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Assets),
  //     },
  //     {
  //       name: SUB_MENU.Infrastructure,
  //       icon: <Infrastructure style={whiteColor} />,
  //       iconBlue: <Infrastructure style={primaryColor} />,
  //       iconLightBlue: <Infrastructure style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Infrastructure),
  //     },
  //   ],
  // },
  // {
  //   name: TITLE_MENU.Reporting,
  //   nameIcon: <Reporting style={whiteColor} />,
  //   nameIconBlack: <Reporting style={blackColor} />,
  //   menu: [
  //     {
  //       name: SUB_MENU.CustomMetrics,
  //       icon: <CM style={whiteColor} />,
  //       iconBlue: <CM style={primaryColor} />,
  //       iconLightBlue: <CM style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.CustomMetrics),
  //     },
  //     {
  //       name: SUB_MENU.Notificiation,
  //       icon: <Notificiation style={whiteColor} />,
  //       iconBlue: <Notificiation style={primaryColor} />,
  //       iconLightBlue: <Notificiation style={primaryLightColor} />,
  //       description: '',
  //       isHideMobile: false,
  //       isActionAvailable: false,
  //       isWorking: false,
  //       routePath: toLowerCaseReplace(SUB_MENU.Notificiation),
  //     },
  //   ],
  // },
]
